# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://dangraf.github.io/fastai_yolov5/"

git_url = "https://github.com/dangraf/fastai_yolov5/tree/master/"

def custom_doc_links(name): return None
